# -*- coding: utf-8 -*-
"""import_data_and_viusalization .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qnAtVJOQ93PBrTubts7IsPhmQQ_0dwDd
"""

import numpy
import pandas
import os
from google.colab import drive
from keras.preprocessing.image import ImageDataGenerator, NumpyArrayIterator
import matplotlib.pyplot as plt
from PIL import Image

drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %pwd
# %cd drive/MyDrive

npzobj = numpy.load('public_data.npz', allow_pickle=True)

npzobj.files

"""npzobj is an object of the class npzfile. by accessing [data] we have a tensor of this sizes:



"""

print(npzobj['data'].shape)
print(npzobj['labels'].shape)

train_generator = ImageDataGenerator(rescale = 1./255)
train_generator = train_generator.flow(
    x=npzobj['data'],
    y=npzobj['labels'],
    batch_size=20,
    shuffle=True,
    sample_weight=None,
    seed=None,
    save_to_dir=None,
    save_prefix='',
    save_format='png',
    ignore_class_split=False,
    subset=None
)

immagine = npzobj['data'][45]
immagine_normalizzata = immagine.astype(numpy.float32) / 255.0  # Normalizzazione dei valori tra 0 e 1

# Plot dell'immagine RGB
plt.imshow(immagine_normalizzata)
string = str ( npzobj['labels'][45])
plt.title(string)
plt.axis('off')  # Rimuove gli assi
plt.show()