def file_upload():

    """import_data_and_viusalization .ipynb

    Automatically generated by Colaboratory.

    Original file is located at
        https://colab.research.google.com/drive/1qnAtVJOQ93PBrTubts7IsPhmQQ_0dwDd
    """

    import numpy
    import pandas
    from keras.preprocessing.image import ImageDataGenerator, NumpyArrayIterator
    import matplotlib.pyplot as plt
    from PIL import Image
    # Commented out IPython magic to ensure Python compatibility.
    # %pwd
    # %cd drive/MyDrive

    npzobj = numpy.load('public_data.npz', allow_pickle=True)

    npzobj.files

    """npzobj is an object of the class npzfile. by accessing [data] we have a tensor of this sizes:
    """

    print(npzobj['data'].shape)
    print(npzobj['labels'].shape)

    immagine = npzobj['data'][45]
    immagine_normalizzata = immagine.astype(numpy.float32) / 255.0  # Normalizzazione dei valori tra 0 e 1

    # Plot dell'immagine RGB
    plt.imshow(immagine_normalizzata)
    string = str ( npzobj['labels'][45])
    plt.title(string)
    plt.axis('off')  # Rimuove gli assi
    plt.show()
    return (npzobj)
